### ISSUE TITLE
Enhancement: move/clone this repo in the libvips org

### ISSUE THREAD

**Issue by lovell** [lovell/package-libvips-darwin#5]
Will require the following (possibly more):

* rename homebrew tap references to `libvips`
* update where resultant binaries are published (currently private S3 bucket)

**Comment by kleisauke** [comment]
For what it's worth, I just had a problem with Homebrew and this custom tap that might be difficult to maintain a libvips tap. It seems that the version numbers of the overwritten formulas from this repo should correspond to the formulas of Homebrew. Otherwise, Homebrew prefers the formula of his own repo.

See for example this Travis build:
https://travis-ci.org/kleisauke/libvips-packaging/builds/549085414

I fixed this by cherry-picking [this commit](https://github.com/Homebrew/homebrew-core/commit/1b2bab2afc8b022a4f7464df4def5c7b5ebd8540) to [my fork](https://github.com/kleisauke/package-libvips-darwin/commit/36096e9c89d5efb3dd3ef10b97bb4fb93dadb3c7), see:
https://travis-ci.org/kleisauke/libvips-packaging/builds/549094767

**Comment by lovell** [comment]
I guess we'll need to watch for upstream changes such as this and patch them. We could probably automate the detection of this.

I've added you to this repo as a collaborator so feel free to apply https://github.com/kleisauke/package-libvips-darwin/commit/36096e9c89d5efb3dd3ef10b97bb4fb93dadb3c7

**Comment by kleisauke** [comment]
Thanks! Applied with commit 36096e9.

I'll see if I can create a bash-script that can detect upstream changes for the overwritten formulas and apply them if necessary.

**Comment by lovell** [comment]
Closing as we can now archive this repo.
